### ISSUE TITLE
Add recent and upcoming events to "News"

### ISSUE THREAD

**Issue by ddjensen** [KDL-umass/kdl-umass.github.io#19]
Akanksha should add her paper presentation last fall and her upcoming trip to Grad Cohort.  I know that there are other events we're missing.  What are they?

**Comment by akanksha95** [comment]
I added mine. We don't have you and Sam going to the PI meeting?

**Comment by ddjensen** [comment]
PI meetings aren't really worth listing.  Paper acceptances, paper presentations, student educational milestones, student attendance at "invitation only" events, and awards are.

**Comment by SamWitty** [comment]
What about invited talks? I gave two last year, one to the MIT probcomp group and one for the GRiD organization at UMass.

**Comment by ddjensen** [comment]
Excellent!  Yes, definitely include those.

**Comment by SamWitty** [comment]
Noted. I'll post the details here, but leave it to someone else to update the site.

11/2/2017 - Sam Witty gave an invited talk for the MIT Probabilistic Computing Project (http://probcomp.csail.mit.edu) on "Computational Representations of Causality".

11/29/2017 - Sam Witty gave a tutorial on "Causal Inference with Graphical Models" for the UMass Graduate Researchers in Data (http://gridclub.io).

**Comment by akanksha95** [comment]
Done!

**Comment by akanksha95** [comment]
Done, @SamWitty!

**Comment by akanksha95** [comment]
Closing this now, feel free to continue adding to it.
