### ISSUE TITLE
people page update

### ISSUE THREAD

**Issue by etosch** [KDL-umass/kdl-umass.github.io#5]
@agentzel @kclary @akanksha95 @SamWitty @ddjensen @etosch 

Update/Add personal page with default information + "Ask me about..." blurb.

**Comment by akanksha95** [comment]
@etosch, can you work on the formatting of this? You have experience with that (and it will take me forever to figure it out).

**Comment by akanksha95** [comment]
It has been fixed and has all of us on the page now 💯 . Thanks @KDL-umass/collaborators 🥇
